In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.full(6,3.1)

array([3.1, 3.1, 3.1, 3.1, 3.1, 3.1])

In [8]:
a = np.array([2,4,5,7])
a

array([2, 4, 5, 7])

In [7]:
a[2]

np.int64(5)

In [9]:
a[2] = 9

In [10]:
a

array([2, 4, 9, 7])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [16]:
# Multidimensional arrays

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
n = np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])
         

In [20]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# acessing 2

n[0,1]

np.int64(2)

In [22]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
n[2]

array([7, 8, 9])

In [25]:
n[:,1]

array([20,  5,  8])

In [30]:
# Random generated arrays
np.random.seed(5)
np.random.rand(5,2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [31]:
np.random.seed(5)
np.random.randn(5,2)

array([[ 0.44122749, -0.33087015],
       [ 2.43077119, -0.25209213],
       [ 0.10960984,  1.58248112],
       [-0.9092324 , -0.59163666],
       [ 0.18760323, -0.32986996]])

In [32]:
np.random.seed(5)
100 * np.random.rand(5,2)

array([[22.19931711, 87.07323062],
       [20.67191553, 91.86109079],
       [48.84111888, 61.17438629],
       [76.59078565, 51.84179879],
       [29.68005016, 18.77212287]])

In [33]:
np.random.seed(5)
np.random.randint(low = 1 , high =10 , size=(5,2))

array([[4, 7],
       [7, 1],
       [9, 5],
       [8, 1],
       [1, 8]])

In [36]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
b = (10 + (a * 2))/10
b

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [38]:
a + b 

array([ 1. ,  2.2,  3.4,  4.6,  5.8,  7. ,  8.2,  9.4, 10.6, 11.8])

In [42]:
# compare arrays
a >= 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
a > b

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [43]:
a[a>b]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a.min()

np.int64(0)

In [45]:
a.max()

np.int64(9)

In [46]:
a.sum()

np.int64(45)

In [47]:
a.mean()

np.float64(4.5)

In [48]:
a.std()

np.float64(2.8722813232690143)

In [49]:
n.sum()

np.int64(63)

In [50]:
n.mean()

np.float64(7.0)