In [2]:
import numpy as np

In [4]:
u = np.array([1,2,3])
v = np.array([4,5,6])

In [5]:
u + v

array([5, 7, 9])

In [6]:
# multiplication 
u * v

array([ 4, 10, 18])

In [7]:
# dot product
def vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0], "Vectors must be the same shape"
    n = u.shape[0]
    result = 0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [8]:
vector_multiplication(u,v)

np.int64(32)

In [9]:
u.dot(v)

np.int64(32)

In [10]:
# natrix multiplication
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])

In [11]:
A.shape

(2, 3)

In [12]:
B.shape

(3, 2)

In [13]:
A.dot(B)

array([[ 58,  64],
       [139, 154]])

In [15]:
I =np.eye(3)

In [19]:
z = A.dot(I)

In [21]:
np.linalg.inv(z)

LinAlgError: Last 2 dimensions of the array must be square